project:
  type: website
  output-dir: docs

website:
  title: "FIShBOT"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Explore"
        href: explore.qmd
      - text: "Contact"
        href: contact.qmd
     

format:
  html:
    lightbox: true
    code-copy: true        # Adds a "copy" button to code chunks
    code-overflow: wrap    # Prevents long Python/R lines from breaking the layout
    code-tools: false       # Adds a "View Source" menu to the page
    theme:
      - cosmo
      - styles.scss
    toc: false

execute:
  freeze: auto
  
  