name: Render and Publish Website
on:
  push:
  branches:
  - website # Only trigger when pushing to this branch

jobs:
  build-deploy:
  runs-on: ubuntu-latest
permissions:
  contents: write
steps:
  - name: Check out repository
uses: actions/checkout@v4

- name: Set up Quarto
uses: quarto-dev/quarto-actions/setup@v2

- name: Render and Publish
uses: quarto-dev/quarto-actions/publish@v2
with:
  target: gh-pages # This creates a hidden branch for the final HTML
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}